language: node_js
node_js:
  - "14"
services:
  - docker
cache:
  directories:
    - node_modules
before_install:
  - yarn install

script:
  - yarn run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t lbt1332051236/tsc:latest .
  - docker push lbt1332051236/tsc:latest
